### ISSUE TITLE
Change dependencies format

### ISSUE THREAD

**Issue by dalance** [dalance/veryl#135]
Currently, name of left hand side is mandatory in `dependencies` section.
It blocks to merge the same indirect dependency through different project.
In the following case, the `common` project should be instantiated at once,
but which namespace should be selected `common` or `cmn`?

* project_x

```toml
project_a = {git = "https://example.com/user/project_a", version = "0.1.0"}
project_b = {git = "https://example.com/user/project_b", version = "0.1.0"}
```

* project_a

```toml
common = {git = "https://example.com/user/common", version = "0.1.0"}
```

* project_b

```toml
cmn = {git = "https://example.com/user/common", version = "0.1.0"}
```

So I'll remove name. The project name of dependencies is used as namespace.
`name` field is optional to avoid namespace conflict.

```
[dependencies]
"https://example.com/user/common1" = "0.1.0"
"https://example.com/user/common2" = {version = "0.1.0", name = "common2"}
"https://example.com/user/common3" = [
    {version = "0.1.0", name = "common3_1"},
    {version = "0.2.0", name = "common3_2"}
]
```
