### ISSUE TITLE
project namespace

### ISSUE THREAD

**Issue by dalance** [dalance/veryl#35]
to avoid name conflict between packages

**Comment by dalance** [comment]
`::` can be used for project namespace resolver like package.

```toml
[dependencies]
prj1 = { git = "" }
```

```
module ModuleA {
    inst a: prj1::ModuleB;
}
```

In SystemVerilog, `::` is replaced with `_`.

```systemverilog
module ModuleA;
    prj1_ModuleB a();
endmodule
```

**Comment by dalance** [comment]
Project name should be added too.

```toml
[project]
name = "sample"

[dependencies]
prj1 = { git = "" }
```

```
module ModuleA {
    inst a: prj1::ModuleB;
}
```

```systemverilog
module sample_ModuleA;
    prj1_ModuleB a();
endmodule
```
