### ISSUE TITLE
project dependency

### ISSUE THREAD

**Issue by dalance** [dalance/veryl#36]

**Comment by dalance** [comment]
The first step will be git path based dependency.

**Comment by dalance** [comment]
```toml
[dependencies]
prj1 = { git = "" }
prj2 = { git = "", rev = "" }
prj3 = { git = "", tag = "" }
prj4 = { git = "", branch = "" }
```
